#!/bin/sh

# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev

# Same for proc and sysfs
/bin/mount -t sysfs sysfs /sys
/bin/mount -t proc proc /proc

echo ""
echo "+---------------------------+"
echo "| Kendryte K210 NOMMU Linux |"
echo "+---------------------------+"
echo "running on real riscv hardware today!"

# switch to getty
exec /sbin/getty -L 115200 ttySIF0 vt102 -n -l /bin/sh
